### ISSUE TITLE
Unable to use version 5.6.16 with action?

### ISSUE THREAD

**Issue by cviebrock** [elastic/elastic-github-actions#17]
I get the following error when trying to use this action with ES 5.6.16, 5.6.15 and a few other 5.x branches:

```
+ docker run --network elastic --rm appropriate/curl --max-time 120 --retry 120 --retry-delay 1 --retry-connrefused --show-error --silent http://es1:9200
Unable to find image 'appropriate/curl:latest' locally

   ...

Digest: sha256:c8bf5bbec6397465a247c2bb3e589bb77e4f62ff88a027175ecb2d9e4f12c9d7
Status: Downloaded newer image for appropriate/curl:latest
curl: (6) Could not resolve host: es1
```

You can see the full logs here: https://github.com/cviebrock/laravel-elasticsearch/runs/2255121033?check_suite_focus=true

Does the action not work with the 5.x ES stack?

**Comment by StrayDragon** [comment]
Same issue, maybe https://github.com/elastic/elastic-github-actions/pull/16 is one of solutions?

**Comment by picandocodigo** [comment]
The action has not been tested with `5.x` versions of the stack and we have no intention to support it for the moment since it's reached it's end of life. See [Elastic product end of life dates](https://www.elastic.co/support/eol) for more information.
