### ISSUE TITLE
Not superuser error.

### ISSUE THREAD

**Issue by ysfkaya** [elastic/elastic-github-actions#21]
I getting an error when I testing it with `act`. 

<img width="1216" alt="screenshot" src="https://user-images.githubusercontent.com/16710972/133977325-555f2771-9170-44d8-bdf6-e377f03f2510.png">

How can I resolve this ?

**Comment by petericebear** [comment]
I have the same issue through act, but I think that is outside of this repository due to the images that act are using are read-only. For local testing I put a # for that line, and the testing works great locally with act then
