### ISSUE TITLE
curl: (7) Failed to connect to es1 port 9200: Host is unreachable

### ISSUE THREAD

**Issue by chrisloftus** [elastic/elastic-github-actions#23]
Latest commit https://github.com/elastic/elastic-github-actions/commit/cd0dfb41acc8f74d65fbee9ad04ce43031fbf488 breaks the default install

```steps:
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 6.2.2
```

Rolled back to previous commit works `uses: elastic/elastic-github-actions/elasticsearch@24006c82ed2f0f1355fce96135f883acf1b1a889`

**Comment by picandocodigo** [comment]
Hi @chrisloftus, is this still an issue for you with the latest updates?

**Comment by chrisloftus** [comment]
@picandocodigo No idea sorry. Left that job.

**Comment by picandocodigo** [comment]
@chrisloftus cool, no worries! Thanks for replying. I'm going to close the issue and if something else comes up, a new issue should be created 👍

**Comment by xmunoz** [comment]
This is still an issue.

https://github.com/xmunoz/rubberband/actions/runs/17382735974/job/49343668505
https://github.com/xmunoz/rubberband/actions/runs/17382469848/job/49342853040

**Comment by Michal-Szczepaniak** [comment]
The issue still persists, i even tried @xmunoz's commit
