### ISSUE TITLE
Is this still under active development?

### ISSUE THREAD

**Issue by maxKimoby** [elastic/elastic-github-actions#33]
Hey! Is this project still maintained/ready to be used in production workflows? 

Thanks!

**Comment by Piedone** [comment]
Would be curious too.

**Comment by picandocodigo** [comment]
Hi, though we haven't updated this project in a while, we're using it for some of our Elasticsearch clients testing on GitHub Actions (e.g. [elasticsearch-ruby](https://github.com/elastic/elasticsearch-ruby/blob/main/.github/workflows/main.yml)). So it's maintained and up to date and working at least with Elasticsearch. I'll try to make some time to go through the current open issues and take a look at the open PR's as soon as I can. Thanks!

**Comment by Piedone** [comment]
Awesome, thank you!
