### ISSUE TITLE
Elasticsearch ≤ 6 is not supported

### ISSUE THREAD

**Issue by delvedor** [elastic/elastic-github-actions#6]
With the current configuration, Elasticserarch will never boot with versions lower than 7, because of the different configuration of the discovery algorithm.

Further reading: https://www.elastic.co/blog/a-new-era-for-cluster-coordination-in-elasticsearch

**Comment by minhtuev** [comment]
Yes I am running into this issue as well

**Comment by minhtuev** [comment]
https://github.com/cisco/mindmeld/runs/586777782
