### ISSUE TITLE
feature request: plugins support

### ISSUE THREAD

**Issue by miyataka** [elastic/elastic-github-actions#9]
some elasticsearch plugin is de facto standard for some people.
for example, analysis-kuromoji for japanese, analysis-nori for korean.
Could you support plugin as action's parameter?

Like these.
- https://github.com/marketplace/actions/run-elasticsearch-with-plugins
- https://github.com/marketplace/actions/setup-elasticsearch-with-plugins

**Comment by miyataka** [comment]
I created prototype branch [here](https://github.com/miyataka/elastic-github-actions/tree/feature/plugin_support).
But Not passed CI. -> [result](https://github.com/miyataka/elastic-github-actions/runs/767647462?check_suite_focus=true)

Because it cannot install plugin on SNAPSHOT version. But WHY this happen?
Please tell me how to fix or workaround.

ref. 
NOT SNAPSHOT version CI result: https://github.com/miyataka/elastic-github-actions/runs/767723298?check_suite_focus=true
SNAPSHOT version CI result: https://github.com/miyataka/elastic-github-actions/runs/767723315?check_suite_focus=true


## how to reproduce
```sh
$ docker run -it docker.elastic.co/elasticsearch/elasticsearch:6.8-SNAPSHOT sh
sh-4.2# elasticsearch-plugin install analysis-kuromoji
ERROR: attempted to install release build of official plugin on snapshot build of Elasticsearch
sh-4.2# exit

$ docker run -it docker.elastic.co/elasticsearch/elasticsearch:6.8.10 sh
Digest: sha256:f8e21f6b2ef75dcda374da505fcb0ff4bf7e8d025f12096c498123fa4e372c1b
Status: Downloaded newer image for docker.elastic.co/elasticsearch/elasticsearch:6.8.10
sh-4.2# elasticsearch-plugin install analysis-kuromoji
-> Downloading analysis-kuromoji from elastic
[=================================================] 100%??
-> Installed analysis-kuromoji
sh-4.2#
```

**Comment by arbourd** [comment]
Ya, this would very helpful as we run some pretty long and dense integration tests inside of Github Actions. We're using @miyataka's fork at the moment (thank you so much for that!)

**Comment by lamasfoker** [comment]
Actually as the action is right now it is possible to install plugins:
```
      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: ${{ env.ELASTICSEARCH_VERSION }}
          plugins: analysis-phonetic analysis-icu
```

The only issue is that the documentation is not up to date.

**Comment by miyataka** [comment]
That's true. It already implemented. Thank you @lamasfoker  for notified to me.
https://github.com/elastic/elastic-github-actions/pull/22
